### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by damianoneill** [chzerv/ansible-role-sysctl#1]
Hi @chzerv thanks for the role, can you tag the repo so that the role can be versioned?

Thanks,
Damian.

**Comment by chzerv** [comment]
Done (I think). I haven't worked with tags/releases before, so please tell me if everything is working as expected.

Also, thank you for opening the first issue!

**Comment by damianoneill** [comment]
Hi @chzerv thanks for doing this.  Normally version is done using [semver](https://semver.org/) so something like v1.0.0  Once the tag is in github, you'll need to go to galaxy and my imports and resync.

**Comment by chzerv** [comment]
Thank you so much for the tips! I can now see the tag in galaxy so i suppose i did it correctly this time.

**Comment by damianoneill** [comment]
Thanks @chzerv looks good.
